export default {
    LOADING_CATEGORIES: "LOADING_CATEGORIES",
    LOAD_CATEGORIES_SUCCESS: "LOAD_CATEGORIES_SUCCESS",
    LOAD_CATEGORIES_FAILURE: "LOAD_CATEGORIES_FAILURE",
    LOAD_PRODUCT_SUCCESS: "sofkau.category.productadded",
    ASSIGN_PRODUCT_SUCCESS: "sofkau.category.productassigned",
}